### ISSUE TITLE
Generating kubernetes jsonschemae doesn't produce the expected output

### ISSUE THREAD

**Issue by evrardjp** [instrumenta/openapi2jsonschema#36]
When following the documentation for producing the jsonschema files (with version 1.18.1), I am not getting the same output as  https://github.com/instrumenta/kubernetes-json-schema/tree/master/v1.18.1-standalone .
For example, I don't get a `deployment-apps-v1.json` file (I don't a get a file with apiversion in the filename, only a file named `deployment.json`).

How should I generate those? Is there something missing on the docs? I tried with the ``--kubernetes`` flag, but same problem.

**Comment by garethr** [comment]
You can see how these files are generated in https://github.com/instrumenta/kubernetes-json-schema/blob/master/build.sh. Hopefully that helps.

**Comment by evrardjp** [comment]
Thanks!

I think it would be better if the docs was updated, so I pushed this PR for you: https://github.com/instrumenta/openapi2jsonschema/pull/37
