### ISSUE TITLE
`"additionalProperties": false`  at root level

### ISSUE THREAD

**Issue by surajnarwade** [instrumenta/openapi2jsonschema#4]
To detect extra fields with `strict` mode, project should inject  `"additionalProperties": false` at root level as well,

I tried manually adding as below in `deployment.json` and it worked :)

```
{
  "type": "object",
  "$schema": "http://json-schema.org/schema#",
      "additionalProperties": false,
...
...
...
```

**Comment by surajnarwade** [comment]
ping @garethr

**Comment by surajnarwade** [comment]
any updates ?

**Comment by garethr** [comment]
Apologies, I'd missed this and not had much time to maintained this project. Should be resolved in https://github.com/instrumenta/openapi2jsonschema/commit/565f4f3ec505f552312284cdb53cabeee4806273.
